(use-modules (gnu packages)
             (guix packages)
             (guix git)
             (guix build-system trivial)
             ((guix licenses)
              #:prefix license:)
             (gnu packages gettext)
             (gnu packages ruby))

(package
  (name "emberb")
  (version "TODO")
  (source (git-checkout (url (dirname (current-filename)))))
  (build-system trivial-build-system)
  (native-inputs (list bundler))
  (home-page "TODO")
  (synopsis "TODO")
  (description "TODO")
  (license license:cc-by4.0))
