#!/usr/bin/env ruby
# frozen_string_literal: true

directories(%w[_po].select { |d| Dir.exist?(d) ? d : UI.warning("Directory #{d} does not exist") })

guard :shell do
  watch(/(.*).po/) { |_m| `make generate_translations` }
end
